version: '3'
services:
  node-app-api:
    build: .
    ports:
      - 3001:3001
    environment:
      - PORT=3001
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gary 
      - MONGO_INITDB_ROOT_PASSWORD=asdfasdf
volumes:
  mongo-db: