version: '3'
services:
  node-app-api:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - .:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=gary
      - MONGO_PASSWORD=asdfasdf
      - MONGO_IP=mongo
      - MONGO_PORT=27017
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gary 
      - MONGO_INITDB_ROOT_PASSWORD=asdfasdf

