version: '3'
services:
  node-app-api:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app:ro
      - /app/node_modules
    environment:
      - PORT=3001 
        # - NODE_ENV=development
        # - MONGO_URL=mongodb://root:example@mongo:27017
        # - JWT_SECRET=secret
    # env_file:
    #   - .env


#     depends_on:
#       - mongo
#   mongo:
#     image: mongo
#     ports:
#       - 27017:27017
#     volumes:
#       - mongo:/data/db
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example

# volumes:
#     mongo:
